BeginnerExercise/Models/ErrorViewModel.cs
namespace BeginnerExercise.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BeginnerExercise/Controllers/Exercise001Controller.cs
using Microsoft.AspNetCore.Mvc;
using System.Runtime.Intrinsics.Arm;

namespace BeginnerExercise.Controllers
{
    public class Exercise001Controller : Controller
    {
       //  string  path = Directory.GetCurrentDirectory()+"Exercise001.txt";
         string  path = "Exercise001.txt";
        List<string> fortuneCookies = new List<string>();
        static int counter = 999;
        public IActionResult Index()
        {
           
            return View();
        }
        public IActionResult RandomFortuneCookie()
        {
            using StreamReader textIn = new(new FileStream(path, FileMode.Open, FileAccess.Read));

            while (textIn.Peek() != -1)
            {
                string row = textIn.ReadLine() ?? "";
                //string[] columns = row.Split(Sep);

                fortuneCookies.Add(row);

            }
           // var random = new Random();

           // var value = random.Next(fortuneCookies.Count());

                   var counter = fortuneCookies.IndexOf(ViewBag.FortuneCookie);


            var random = new Random();
            var value = 0;
           do
           {
                 value = random.Next(fortuneCookies.Count());

           } while (counter==value);


          

         

  
            ViewBag.FortuneCookie= fortuneCookies[value];
            return View(nameof(Index));
        }
    }
}

BeginnerExercise/Controllers/HomeController.cs
using BeginnerExercise.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BeginnerExercise.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BeginnerExercise/Views/Exercise001/Index.cshtml
<h1>Fortune Cookies</h1>

<hr />
<p>@ViewBag.FortuneCookie</p>

<form method="get" asp-action="RandomFortuneCookie">
    <button>Submit</button>
</form>

BeginnerExercise/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}





<h1>Exercise 001 <a asp-action="Index" asp-controller="Exercise001">Go</a></h1>

BeginnerExercise/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeginnerExercise</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BeginnerExercise.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeginnerExercise</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - BeginnerExercise - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>